# Generated by Django 5.2.6 on 2025-09-22 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ('name',), 'verbose_name': 'Work', 'verbose_name_plural': 'Works'},
        ),
        migrations.RemoveField(
            model_name='work',
            name='description',
        ),
        migrations.RemoveField(
            model_name='work',
            name='place',
        ),
        migrations.AddField(
            model_name='work',
            name='name',
            field=models.CharField(default='Work', max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='work',
            name='slug',
            field=models.SlugField(default='Work', max_length=250, unique=True),
        ),
        migrations.CreateModel(
            name='Work_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_images')),
                ('description', models.TextField()),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='screen.work')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkImage',
        ),
    ]
