# Generated by Django 5.2.6 on 2025-09-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0002_alter_work_options_remove_work_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='slug',
            field=models.SlugField(default='Work', max_length=250),
        ),
    ]
