# Generated by Django 5.2.6 on 2025-09-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0003_alter_work_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work_details',
            options={'ordering': ('work',), 'verbose_name': 'Work Detail', 'verbose_name_plural': 'Work Details'},
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
