# Generated by Django 3.2.25 on 2025-09-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0004_alter_work_details_options_alter_work_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_images')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'art',
                'verbose_name_plural': 'arts',
            },
        ),
    ]
