# Generated by Django 3.2.25 on 2025-09-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0005_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
