# Generated by Django 3.2.25 on 2025-09-23 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0006_alter_art_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoveAndWar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('side_image', models.ImageField(upload_to='work_images')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoveAndWarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_images')),
                ('love_and_war', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='screen.loveandwar')),
            ],
        ),
    ]
