# Generated by Django 3.2.25 on 2025-09-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0007_loveandwar_loveandwarimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itswhatido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('side_image', models.ImageField(upload_to='work_images')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
