# Generated by Django 3.2.25 on 2025-09-23 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0008_itswhatido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itswhatido',
            options={'verbose_name': 'its what i do', 'verbose_name_plural': 'its what i do'},
        ),
    ]
