# Generated by Django 3.2.25 on 2025-09-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0010_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Exhibition',
        ),
        migrations.AlterModelOptions(
            name='exhibition',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contac'},
        ),
    ]
