# Generated by Django 3.2.25 on 2025-09-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0012_auto_20250923_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='title2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='awards',
            name='title3',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
