# Generated by Django 3.2.25 on 2025-09-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0013_auto_20250923_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='title2description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='awards',
            name='title3description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='awards',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
